name: Check Outdated Dependencies

on:
  schedule:
    # Run the workflow every day at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Check outdated dependencies
        run: npm outdated --json > outdated.json || true

      - name: Create branches for outdated dependencies
        run: |
          if [ -s outdated.json ]; then
            ./createDependencyBranches.sh
            echo "HAS_OUTDATED_DEPENDENCIES=true" >> $GITHUB_ENV
          else
            echo "HAS_OUTDATED_DEPENDENCIES=false" >> $GITHUB_ENV
          fi

      - name: Trigger PR creation workflow
        if: env.HAS_OUTDATED_DEPENDENCIES == 'true'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: outdated-dependencies
          client-payload: '{"has_outdated_dependencies": "true"}'
