name: Create Pull Requests for Dependency Updates

on:
  repository_dispatch:
    types:
      - outdated-dependencies

jobs:
  create_prs:
    runs-on: ubuntu-latest
    if: github.event.client_payload.has_outdated_dependencies == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: git fetch --no-tags --prune --depth=1 origin '+refs/heads/*:refs/remotes/origin/*'

      - name: Get list of outdated dependency branches
        id: get_branches
        run: |
          branches=$(git branch --remote --list 'origin/update-*' | sed 's/origin\///')
          branches="${branches//$'\n'/,}"
          echo "::set-output name=branches::$branches"

      - name: Create Pull Requests
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ""
          delete-branch: true
          title: "chore: update {name} to {latest_version}"
          commit-message: "chore: update {name} to {latest_version}"
          body: "This PR updates {name} to {latest_version}"
          labels: "dependencies"
          base: "main"
        env:
          BRANCHES: ${{ steps.get_branches.outputs.branches }}
