name: Run Tests and Update PR Description

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled

jobs:
  test-and-update-pr:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        id: run_tests
        continue-on-error: true
        run: npm test

      - name: Update PR description
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ steps.run_tests.outcome }}" == "success" ]; then
            test_result="✅ **Tests Passed**"
          else
            test_result="❌ **Tests Failed**"
          fi

          pr_number=$(jq --raw-output .number "$GITHUB_EVENT_PATH")
          pr_description=$(curl -s -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number | jq -r '.body')
          updated_description="${pr_description}\n\n${test_result}"

          curl -s -X PATCH -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" \
            -d "{\"body\": \"$updated_description\"}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number
